adding test release

diff --git a/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb b/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
--- a/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
+++ b/jobs/cf-mysql-broker/templates/cf-mysql-broker_ctl.erb
@@ -16,6 +16,11 @@ export SETTINGS_PATH=$JOB_DIR/config/settings.yml
 export HOME=/home/vcap
 export JOB_INDEX=<%= index %>
 
+source /var/vcap/packages/cf-mysql-common/pid_utils.sh
+source /var/vcap/packages/cf-mysql-common/logging.sh
+
+output_to_logfiles ${LOG_DIR}
+
 # add mysql to path
 if [ ! -f /usr/local/bin/mysql ]; then
   echo "Adding mysql to path"
@@ -26,60 +31,62 @@ case $1 in
 
   start)
     mkdir -p $RUN_DIR
+    chown -R vcap:vcap $RUN_DIR
     mkdir -p $LOG_DIR
+    chown -R vcap:vcap $LOG_DIR
 
-    # Start syslog forwarding
-    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
+    pushd $PACKAGE_DIR
+      # Run the migrations only on the first node
+      if [ $JOB_INDEX -eq 0 ]; then
+          # Needed because rake db:migrate attempts to rewrite schema.rb file
+          # which is currently owned by root
+          #
+          # Needs to live here instead of above because chown -R does not follow symlinks
+          chown -R vcap:vcap .
 
-    # Run the migrations only on the first node
-    if [ $JOB_INDEX -eq 0 ]; then
-      pushd $PACKAGE_DIR
+          # Create DB and run migrations
+          set +e
+          su - vcap -p -c -o pipefail "PATH=$PATH bundle exec rake db:create \
+              >> $LOG_DIR/db_migrate.combined.log 2>&1"
 
-        # Create DB and run migrations
-        set +e
-        bundle exec rake db:create 2>&1 \
-            | tee -a $LOG_DIR/db_migrate.combined.log \
-            | logger -p local1.error -t mysql-broker-dbcreate
+          su - vcap -p -c -o pipefail "PATH=$PATH bundle exec rake db:migrate \
+              >> $LOG_DIR/db_migrate.combined.log 2>&1"
 
-        bundle exec rake db:migrate 2>&1 \
-            | tee -a $LOG_DIR/db_migrate.combined.log \
-            | logger -p local1.error -t mysql-broker-dbmigrate
+          EXIT_STATUS=$?
+          set -e
 
-        EXIT_STATUS=$?
-        set -e
+          if [ $EXIT_STATUS != 0 ]; then
+            echo "Migrations failed at `date`" \
+                >> $LOG_DIR/db_migrate.combined.log
+            exit 1
+          fi
 
-        if [ $EXIT_STATUS != 0 ]; then
-          echo "Migrations failed at `date`" \
-              | tee -a $LOG_DIR/db_migrate.combined.log \
-              | logger -p local1.error -t mysql-broker-dbmigrate
-          exit 1
-        fi
+          # Sync size of existing service instances to match plans in manifest
+          set +e
+          su - vcap -p -c -o pipefail "PATH=$PATH bundle exec rake broker:sync_plans_in_db \
+              >> $LOG_DIR/cf-mysql-broker.log 2>&1"
 
-        # Sync size of existing service instances to match plans in manifest
-        set +e
-        bundle exec rake broker:sync_plans_in_db 2>&1 \
-            | tee -a $LOG_DIR/cf-mysql-broker.log \
-            | logger -p local1.error -t mysql-broker-plans
+          EXIT_STATUS=$?
+          set -e
 
-        EXIT_STATUS=$?
-        set -e
+          if [ $EXIT_STATUS != 0 ]; then
+            echo "Failed to sync broker plans at `date`" \
+                >> $LOG_DIR/cf-mysql-broker.log
+            exit 1
+          fi
+      fi
 
-        if [ $EXIT_STATUS != 0 ]; then
-          echo "Failed to sync broker plans at `date`" \
-              | tee -a $LOG_DIR/cf-mysql-broker.log \
-              | logger -p local1.error -t mysql-broker-plans
-          exit 1
-        fi
-      popd
-    fi
+      su - vcap -p -c -o pipefail "PATH=$PATH bundle exec rake table_locks:update_table_lock_permissions \
+        >> $LOG_DIR/cf-mysql-broker.log 2>&1"
 
-    bundle exec unicorn -c $JOB_DIR/config/unicorn.conf.rb 2>&1 \
-        | tee -a $LOG_DIR/cf-mysql-broker.log \
-        | logger -p local1.error -t mysql-broker &
+    popd
+
+    su - vcap -p -c -o pipefail "PATH=$PATH bundle exec unicorn -c $JOB_DIR/config/unicorn.conf.rb \
+        >> $LOG_DIR/cf-mysql-broker.log 2>&1 &"
     ;;
 
   stop)
-    kill -QUIT `cat $PIDFILE`
+    kill_and_wait "${PIDFILE}"
     ;;
 
   *)
